<?php $code = $block->escapeHtml($block->getMethodCode()); ?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */
echo $code; ?>" style="display: none">
    <div class="field-type radio admin__field _required">
        <span class="admin__field-label">
            <span><?php echo __('Workflow Type'); ?></span>
        </span>
        <div class="admin__field-control">
            <?php foreach ($block->getCustomerTypes() as $customerType): ?>
                <div>
                    <input type="radio" id="<?php /* @noEscape */
                    echo $code; ?>_customer_type_<?php echo strtolower($customerType['value']); ?>"
                           name="payment[<?php /* @noEscape */
                           echo $code; ?>_customer_type]" value="<?php echo $customerType['value']; ?>"
                           class="admin__control-radio required-entry" data-field-class="field-type-<?php echo strtolower($customerType['value']); ?>"
                            <?php if ( strtolower($customerType['value'] == $block->getInfoData($code . '_customer_type'))): ?>
                            checked
                            <?php endif;?>
                    />
                    <label class="admin__field-label"
                           for="<?php /* @noEscape */
                           echo $code; ?>_customer_type_<?php echo strtolower($customerType['value']); ?>">
                        <span><?php echo $block->escapeHtml($customerType['label']); ?></span>
                    </label>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="field-type admin__field _required field-type-b" style="display: none">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_chamber_of_commerce">
            <span><?php echo $block->escapeHtml(__('Chamber of commerce')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_chamber_of_commerce" name="payment[<?php /* @noEscape */
            echo $code; ?>_chamber_of_commerce]"
                   title="<?php echo $block->escapeHtml(__('Chamber of commerce')); ?>" class="admin__control-text"/>
        </div>
    </div>

    <div class="field-type radio admin__field _required field-type-p" style="display: none">
        <span class="admin__field-label">
            <span><?php echo __('Sex'); ?></span>
        </span>
        <div class="admin__field-control">
            <div>
                <input type="radio" id="<?php /* @noEscape */
                echo $code; ?>_customer_sex_m"
                       name="payment[<?php /* @noEscape */
                       echo $code; ?>_customer_sex]" value="M"
                       class="admin__control-radio"
                    <?php if ('M' == $block->getInfoData($code . '_customer_sex')): ?>
                        checked
                    <?php endif;?>
                />
                <label class="admin__field-label"
                       for="<?php /* @noEscape */
                       echo $code; ?>_customer_sex_m">
                    <span><?php echo $block->escapeHtml(__('Man')); ?></span>
                </label>
            </div>
            <div>
                <input type="radio" id="<?php /* @noEscape */
                echo $code; ?>_customer_sex_f"
                       name="payment[<?php /* @noEscape */
                       echo $code; ?>_customer_sex]" value="F"
                       class="admin__control-radio"
                    <?php if ('F' == $block->getInfoData($code . '_customer_sex')): ?>
                        checked
                    <?php endif;?>
                />
                <label class="admin__field-label"
                       for="<?php /* @noEscape */
                       echo $code; ?>_customer_sex_f">
                    <span><?php echo $block->escapeHtml(__('Female')); ?></span>
                </label>
            </div>
        </div>
    </div>

    <div class="field-type admin__field date _required field-type-p" style="display: none">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_birthdate">
            <span><?php echo $block->escapeHtml(__('Birthdate')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_birthdate" name="payment[<?php /* @noEscape */
            echo $code; ?>_customer_birthdate]"
                   title="<?php echo $block->escapeHtml(__('Birthdate')); ?>" class="admin__control-text"
            value="<?php echo $block->getInfoData($code . '_customer_birthdate'); ?>"
            />
        </div>
    </div>
    <div class="field-type admin__field required _required">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_street_name">
            <span><?php echo $block->escapeHtml(__('Street name')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_street_name" name="payment[<?php /* @noEscape */
            echo $code; ?>_street]"
                   title="<?php echo $block->escapeHtml(__('Street name')); ?>" class="required-entry admin__control-text"
                   value="<?php echo $block->getInfoData($code . '_street'); ?>"
            />
        </div>
    </div>

    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_house_number">
            <span><?php echo $block->escapeHtml(__('House number')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_house_number" name="payment[<?php /* @noEscape */
            echo $code; ?>_house_number]"
                   title="<?php echo $block->escapeHtml(__('House number')); ?>" class="required-entry admin__control-text"
                   value="<?php echo $block->getInfoData($code . '_house_number'); ?>"
            />
        </div>
    </div>

    <div class="field-type admin__field">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_house_extension">
            <span><?php echo $block->escapeHtml(__('House extension')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_house_extension" name="payment[<?php /* @noEscape */
            echo $code; ?>_house_extension]"
                   title="<?php echo $block->escapeHtml(__('House extension')); ?>" class="admin__control-text"
                   value="<?php echo $block->getInfoData($code . '_house_extension'); ?>"
            />
        </div>
    </div>

    <h3><?php echo $block->escapeHtml(__('Delivery Address')); ?></h3>

    <div class="field-type admin__field">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_delivery_street_name">
            <span><?php echo $block->escapeHtml(__('Delivery street name')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_delivery_street_name" name="payment[<?php /* @noEscape */
            echo $code; ?>_delivery_address_street]"
                   title="<?php echo $block->escapeHtml(__('Delivery street name')); ?>" class="admin__control-text"
                   value="<?php echo $block->getInfoData($code . '_delivery_address_street'); ?>"
            />
        </div>
    </div>

    <div class="field-type admin__field">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_delivery_house_number">
            <span><?php echo $block->escapeHtml(__('Delivery house number')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_delivery_house_number" name="payment[<?php /* @noEscape */
            echo $code; ?>_delivery_address_housenumber]"
                   title="<?php echo $block->escapeHtml(__('Delivery house number')); ?>" class="admin__control-text"
                   value="<?php echo $block->getInfoData($code . '_delivery_address_housenumber'); ?>"
            />
        </div>
    </div>

    <div class="field-type admin__field">
        <label class="admin__field-label" for="<?php /* @noEscape */
        echo $code; ?>_delivery_house_extension">
            <span><?php echo $block->escapeHtml(__('Delivery house Extension')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */
            echo $code; ?>_delivery_house_extension" name="payment[<?php /* @noEscape */
            echo $code; ?>_delivery_address_housenumber_extension]"
                   title="<?php echo $block->escapeHtml(__('Delivery house Extension')); ?>"
                   value="<?php echo $block->getInfoData($code . '_delivery_address_housenumber_extension'); ?>"
                   class="admin__control-text"/>
        </div>
    </div>
    <input type="hidden" name="payment[<?php /* @noEscape */
    echo $code; ?>_validate_order]" value="1"/>
</fieldset>
<script>
    var order = window.order;
    require(['jquery'], function ($) {
        var billinkPaymentForm = {
            init: function () {
                this.initEvents();
                this.initDatepicker();
                <?php if ($type = $block->getInfoData($code . '_customer_type')): ?>
                this.resetFields('field-type-<?php echo strtolower($type); ?>');
                <?php endif;?>
            },

            initEvents: function () {
                var self = this;
                $('input[name^="payment[<?php /* @noEscape */
                    echo $code; ?>_customer_type]"').on('change', function (e) {
                    var fieldClass = $(this).data('field-class');

                    setTimeout(function () {
                        order.loadArea(['totals'], true, {});
                    }, 500);

                    self.resetFields(fieldClass);

                });
            },

            initDatepicker: function () {
                $('.date input').datepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+00",
                    dateFormat: "yy-mm-dd"
                })
            },

            resetFields: function (fieldClass) {
                $('.field-type-p, .field-type-b').hide();
                $('.' + fieldClass).show();
            }
        }

        billinkPaymentForm.init();
    })
</script>