<?php /** @var $block \Billink\Billink\Block\Adminhtml\System\Config\Validate\SyncSettings */ ?>

<?= $block->getButtonHtml() ?>
<span id="credentials_message_span" class="message_span">
    <span class="validation-message error" style="display: none;"></span>
    <span class="validation-message success" style="display: none;"></span>
</span>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        jQuery('#sync_settings').click(function () {
            var params = {
                form_key: "<?= $block->getFormKey(); ?>",
                isAjax: true,
                websiteId: "<?= $block->getRequest()->getParam('website'); ?>"
            };

            jQuery.ajax({
                showLoader: true,
                url: "<?= $block->getAjaxUrl(); ?>",
                data: params,
                dataType: 'json'
            }).done(function (response) {
                if(response.error === true) {
                    jQuery('#credentials_message_span .success').hide();
                    jQuery('#credentials_message_span .error').text(response.message).fadeIn(200);
                } else {
                    jQuery('#credentials_message_span .error').hide();
                    jQuery('#credentials_message_span .success').text(response.message).fadeIn(200);
                }
            });
        });

    });
</script>
